"""Cursor execution bridge adapter for ACW real patch generation."""

from __future__ import annotations

import hashlib
import logging
import re
import subprocess
import uuid
from pathlib import Path
from typing import Any

from app.services.cursor_execution_bridge import (
    capture_diff,
    cleanup_staging,
    invoke_cursor_cli,
    is_bridge_enabled,
    provision_staging_workspace,
    require_cursor_auth,
)

logger = logging.getLogger(__name__)

_MAX_GENERATION_ATTEMPTS = 2

_PLACEHOLDER_MARKERS = (
    "# TODO: implement validated change",
    "Generated by patch_agent",
    "NOT APPLIED",
    "requires human approval before application",
    "Jarvis Phase 4 proposed patch",
)

_PLACEHOLDER_LINE = re.compile(r"^\+\s*#.*(?:TODO|placeholder|NOT APPLIED)", re.IGNORECASE)


class PlaceholderPatchError(ValueError):
    """Raised when bridge output is empty, comment-only, or placeholder."""

    def __init__(
        self,
        message: str,
        *,
        generation_attempts: int = 1,
        retry_used: bool = False,
        retry_reason: str | None = None,
    ) -> None:
        super().__init__(message)
        self.generation_attempts = generation_attempts
        self.retry_used = retry_used
        self.retry_reason = retry_reason


def _parse_files_from_diff(diff: str) -> list[str]:
    files: list[str] = []
    for line in diff.splitlines():
        if line.startswith("+++ b/"):
            path = line[6:].strip()
            if path and path != "/dev/null":
                files.append(path)
    return files


def _is_comment_only_diff(diff: str) -> bool:
    """True when every added line is a comment or blank."""
    added = [ln[1:] for ln in diff.splitlines() if ln.startswith("+") and not ln.startswith("+++")]
    if not added:
        return True
    substantive = [
        ln for ln in added if ln.strip() and not ln.strip().startswith("#") and not _PLACEHOLDER_LINE.match("+" + ln)
    ]
    return len(substantive) == 0


def validate_patch_diff(diff: str) -> None:
    """Fail closed on empty, comment-only, or placeholder patches."""
    content = (diff or "").strip()
    if not content:
        raise PlaceholderPatchError("empty diff from Cursor bridge")
    upper = content.upper()
    for marker in _PLACEHOLDER_MARKERS:
        if marker.upper() in upper:
            raise PlaceholderPatchError(f"placeholder patch detected: {marker!r}")
    if _is_comment_only_diff(content):
        raise PlaceholderPatchError("comment-only diff — no substantive code changes")


def is_retryable_placeholder_error(exc: PlaceholderPatchError) -> bool:
    """Whether ACW should retry Cursor generation once with a stricter prompt."""
    return True


def build_acw_retry_prompt(
    *,
    objective: str,
    plan: dict[str, Any],
    evidence: dict[str, Any],
    target_files: list[str] | None = None,
    rejection_reason: str,
) -> str:
    """Stricter follow-up prompt after placeholder/comment-only rejection."""
    base = build_acw_prompt(
        objective=objective,
        plan=plan,
        evidence=evidence,
        target_files=target_files,
    )
    scoped = target_files or (evidence.get("code_references") or [])[:5]
    scoped_lines = "\n".join(f"- {f}" for f in scoped) or "- Only files required by the objective"
    return f"""{base}

## RETRY — previous patch rejected
Reason: {rejection_reason.strip()}

Your previous output was rejected. Generate a corrected patch that satisfies ALL of:
- Make a real code change (add/modify/delete executable code), not comment-only edits.
- No placeholder text, TODO stubs, or markers like "NOT APPLIED".
- No unrelated formatting, drive-by refactors, or whitespace-only churn.
- Do not create new files unless the objective explicitly requires them.
- Edit only within these scoped files:
{scoped_lines}
"""


def _reset_staging_workspace(staging_path: Path) -> None:
    """Discard prior Cursor edits before a generation retry."""
    subprocess.run(
        ["git", "reset", "--hard", "HEAD"],
        cwd=str(staging_path),
        capture_output=True,
        text=True,
        timeout=60,
        check=False,
    )
    subprocess.run(
        ["git", "clean", "-fd"],
        cwd=str(staging_path),
        capture_output=True,
        text=True,
        timeout=60,
        check=False,
    )


def _run_bridge_generation_attempt(
    staging_path: Path,
    *,
    task_id: str,
    prompt: str,
) -> tuple[str, dict[str, Any]]:
    """Invoke Cursor, capture diff, validate. Returns diff text and invoke metadata."""
    invoke_result = invoke_cursor_cli(staging_path, prompt, task_id=task_id)
    if not invoke_result.get("success"):
        err = invoke_result.get("error") or "Cursor CLI failed"
        raise RuntimeError(f"Cursor bridge invoke failed: {err}")

    diff_path = capture_diff(staging_path, task_id)
    if diff_path is None or not diff_path.exists():
        raise PlaceholderPatchError("empty diff from Cursor bridge")

    diff_content = diff_path.read_text(encoding="utf-8")
    validate_patch_diff(diff_content)
    return diff_content, invoke_result


def build_acw_prompt(
    *,
    objective: str,
    plan: dict[str, Any],
    evidence: dict[str, Any],
    target_files: list[str] | None = None,
) -> str:
    """Build a Cursor CLI prompt from objective, plan, and fused evidence."""
    refs = evidence.get("code_references") or []
    files_hint = target_files or refs[:5]
    steps = plan.get("steps") or []
    step_lines = "\n".join(f"- {s.get('description', s)}" for s in steps[:8]) if steps else "- Implement the objective"
    prod = evidence.get("production_evidence") or []
    prod_lines = "\n".join(f"- {p.get('source')}: {p.get('detail', '')[:200]}" for p in prod[:5])

    return f"""# Autonomous Coding Workflow — implement change (LAB sandbox)

## Objective
{objective}

## Plan
{step_lines}

## Target files (prefer these if applicable)
{chr(10).join(f'- {f}' for f in files_hint) or '- Infer from repository context'}

## Repository context
Modules indexed: {(evidence.get('repository_context') or {}).get('modules_count', 0)}

## Production evidence (read-only context)
{prod_lines or '- None collected'}

## Requirements
- Make real, substantive code changes (not comments or TODO placeholders).
- Do not modify trading logic, signal monitor, exchange_sync, secrets, or production deploy scripts.
- Do not add placeholder comments like "# TODO: implement validated change".
- Keep changes minimal and focused on the objective.
"""


def generate_patch_via_bridge(
    task_id: str,
    *,
    objective: str,
    plan: dict[str, Any],
    evidence: dict[str, Any],
    target_files: list[str] | None = None,
) -> dict[str, Any]:
    """
    Provision staging, invoke Cursor CLI, capture diff.

    Uses bridge sub-functions directly (patch generation precedes human approval).
    """
    if not is_bridge_enabled():
        raise RuntimeError("CURSOR_BRIDGE_ENABLED not set")
    require_cursor_auth()

    staging_path = provision_staging_workspace(task_id)
    if not staging_path:
        raise RuntimeError("staging provision failed for Cursor bridge")

    prompt = build_acw_prompt(
        objective=objective,
        plan=plan,
        evidence=evidence,
        target_files=target_files,
    )
    retry_used = False
    retry_reason: str | None = None
    generation_attempts = 0
    last_placeholder_error: PlaceholderPatchError | None = None
    invoke_result: dict[str, Any] = {}

    try:
        for attempt in range(_MAX_GENERATION_ATTEMPTS):
            generation_attempts = attempt + 1
            if attempt > 0:
                retry_used = True
                _reset_staging_workspace(staging_path)
                prompt = build_acw_retry_prompt(
                    objective=objective,
                    plan=plan,
                    evidence=evidence,
                    target_files=target_files,
                    rejection_reason=str(last_placeholder_error),
                )
                logger.info(
                    "acw_patch_bridge: retrying generation task_id=%s attempt=%d reason=%s",
                    task_id,
                    generation_attempts,
                    last_placeholder_error,
                )

            try:
                diff_content, invoke_result = _run_bridge_generation_attempt(
                    staging_path,
                    task_id=task_id,
                    prompt=prompt,
                )
                break
            except PlaceholderPatchError as exc:
                last_placeholder_error = exc
                if attempt + 1 < _MAX_GENERATION_ATTEMPTS and is_retryable_placeholder_error(exc):
                    retry_reason = str(exc)
                    continue
                raise PlaceholderPatchError(
                    str(exc),
                    generation_attempts=generation_attempts,
                    retry_used=retry_used or generation_attempts > 1,
                    retry_reason=retry_reason,
                ) from exc

        target = target_files or _parse_files_from_diff(diff_content)
        content_hash = hashlib.sha256(diff_content.encode()).hexdigest()[:16]
        risk_score = min(100, 20 + len(target) * 8)

        return {
            "patch_id": str(uuid.uuid4()),
            "objective": objective,
            "target_files": target,
            "unified_diff": diff_content,
            "patch_summary": f"Cursor bridge patch: {len(target)} file(s), {len(diff_content)} bytes",
            "revision": 1,
            "content_hash": content_hash,
            "source": "cursor_bridge",
            "staging_path": str(staging_path),
            "invoke_output_len": len(invoke_result.get("output") or ""),
            "generation_attempts": generation_attempts,
            "retry_used": retry_used,
            "retry_reason": retry_reason if retry_used else None,
            "risk_assessment": {
                "risk_score": risk_score,
                "risk_level": "low" if risk_score < 40 else ("medium" if risk_score < 70 else "high"),
                "factors": ["cursor_bridge_generated"] + (["cursor_bridge_retry"] if retry_used else []),
            },
            "estimated_impact": {"auto_apply": False, "files_count": len(target)},
        }
    finally:
        cleanup_staging(task_id)
