"""
Secure Telegram bot token loading.

Priority: TELEGRAM_BOT_TOKEN → TELEGRAM_BOT_TOKEN_DEV → interactive popup.
Never logs or persists the full token.
"""

from __future__ import annotations

import logging
import os
from typing import Optional

logger = logging.getLogger(__name__)

# Mask length for display (e.g. "AAHaawKlho")
MASK_LENGTH = 10


def mask_token(token: Optional[str]) -> str:
    """
    Return a safe mask of the token for logging. Never log the full token.

    Example: "123456789:ABCdefGHI-jklmnopqrstuvwxyz" → "123456789:"
    """
    if not token or not isinstance(token, str):
        return "(none)"
    if len(token) <= MASK_LENGTH:
        return "*" * len(token)
    return token[:MASK_LENGTH] + "..."


def ask_secret_via_popup(title: str, prompt: str) -> Optional[str]:
    """
    Show a password-style popup to request a secret from the operator.
    Tries: tkinter → prompt_toolkit → getpass. Never logs or persists the value.

    Args:
        title: Dialog window title
        prompt: Message shown above the input field

    Returns:
        Entered secret or None if cancelled/failed
    """
    def _via_tkinter() -> Optional[str]:
        try:
            import tkinter as tk
            from tkinter import simpledialog

            root = tk.Tk()
            root.withdraw()
            root.attributes("-topmost", True)

            class PasswordDialog(simpledialog.Dialog):
                def __init__(self, parent, dialog_title: str, dialog_prompt: str):
                    self.dialog_prompt = dialog_prompt
                    self.result_value: Optional[str] = None
                    super().__init__(parent, dialog_title)

                def validate(self):
                    return True

                def body(self, master):
                    tk.Label(master, text=self.dialog_prompt, justify="left").grid(row=0, column=0, padx=5, pady=5)
                    self.entry = tk.Entry(master, width=50, show="*")
                    self.entry.grid(row=1, column=0, padx=5, pady=5)
                    return self.entry

                def apply(self):
                    self.result_value = self.entry.get().strip()

            dlg = PasswordDialog(root, title=title, dialog_prompt=prompt)
            root.destroy()
            return dlg.result_value if dlg.result_value else None
        except Exception as e:
            logger.debug("tkinter secret dialog failed: %s", e)
            return None

    def _via_prompt_toolkit() -> Optional[str]:
        try:
            from prompt_toolkit import prompt
            val = prompt(f"{prompt}: ", is_password=True)
            return val.strip() if val else None
        except ImportError:
            return None
        except Exception as e:
            logger.debug("prompt_toolkit secret input failed: %s", e)
            return None

    def _via_getpass() -> Optional[str]:
        try:
            import getpass
            val = getpass.getpass(f"{prompt}: ")
            return val.strip() if val else None
        except Exception as e:
            logger.debug("getpass secret input failed: %s", e)
            return None

    result = _via_tkinter()
    if result is not None:
        return result
    result = _via_prompt_toolkit()
    if result is not None:
        return result
    return _via_getpass()


def ask_atp_secret() -> Optional[str]:
    """
    Popup to request the ATP secret (e.g. for replacing or entering a project secret).
    Never logs or persists the value.
    """
    return ask_secret_via_popup(
        title="ATP Secret Required",
        prompt="Paste the ATP secret to use",
    )


def _get_token_via_tkinter() -> Optional[str]:
    """Try tkinter GUI for token input. Returns None if failed or cancelled."""
    return ask_secret_via_popup(
        title="ATP Telegram Bot Token Required",
        prompt="Paste the Telegram Bot Token generated by BotFather",
    )


def _get_token_via_prompt_toolkit() -> Optional[str]:
    """Try prompt_toolkit for masked terminal input. Returns None if failed or cancelled."""
    try:
        from prompt_toolkit import prompt

        token = prompt(
            "Paste the Telegram Bot Token generated by BotFather: ",
            is_password=True,
        )
        return token.strip() if token else None
    except ImportError:
        return None
    except Exception as e:
        logger.debug("prompt_toolkit token input failed: %s", e)
        return None


def _get_token_via_terminal() -> Optional[str]:
    """Fallback: terminal input with getpass (masked)."""
    try:
        import getpass

        token = getpass.getpass("Paste the Telegram Bot Token generated by BotFather: ")
        return token.strip() if token else None
    except Exception as e:
        logger.debug("getpass token input failed: %s", e)
        return None


def _get_token_interactive() -> Optional[str]:
    """
    Open a popup or terminal prompt asking for the token.
    Tries: tkinter → prompt_toolkit → getpass.
    """
    token = _get_token_via_tkinter()
    if token:
        return token

    token = _get_token_via_prompt_toolkit()
    if token:
        return token

    token = _get_token_via_terminal()
    return token


def get_telegram_token() -> Optional[str]:
    """
    Get the Telegram bot token for polling and command responses. Never writes it to disk or logs it.

    Priority:
    0. FORCE_TELEGRAM_TOKEN_PROMPT=true → always prompt (ignores env)
    1. AWS + TELEGRAM_ATP_CONTROL_BOT_TOKEN → use for polling (commands go to @ATP_control_bot)
    2. TELEGRAM_BOT_TOKEN
    3. TELEGRAM_BOT_TOKEN_DEV
    4. TELEGRAM_ATP_CONTROL_BOT_TOKEN (non-AWS: when TELEGRAM_BOT_TOKEN not set)
    5. TELEGRAM_CLAW_BOT_TOKEN (Claw fallback)
    6. Interactive popup (tkinter → prompt_toolkit → terminal)

    On AWS, ATP Control is preferred over TELEGRAM_BOT_TOKEN so /task updates reach backend-aws
    instead of only the trading bot. Trading alerts still use TELEGRAM_BOT_TOKEN via telegram_notifier.
    """
    force_prompt = os.getenv("FORCE_TELEGRAM_TOKEN_PROMPT", "false").lower() == "true"
    if force_prompt:
        logger.info("[TG][CONFIG] force_token_prompt=true")
        token = _get_token_interactive()
        if token:
            logger.info("[TG] Token received via interactive prompt (masked: %s)", mask_token(token))
        else:
            logger.warning("[TG] No token provided - Telegram disabled")
        return token

    # AWS PROD: /task and other commands are sent to @ATP_control_bot. If we poll TELEGRAM_BOT_TOKEN
    # (trading/alerts bot) instead, those updates never reach backend-aws — another consumer (e.g.
    # OpenClaw on LAB with the ATP Control token) may answer /task and try read-only workspace edits.
    try:
        from app.core.runtime import is_aws_runtime

        if is_aws_runtime():
            atp = (os.getenv("TELEGRAM_ATP_CONTROL_BOT_TOKEN") or "").strip()
            if atp:
                logger.info(
                    "[TG][CONFIG] AWS polling token=TELEGRAM_ATP_CONTROL_BOT_TOKEN "
                    "(commands /task go to this bot; TELEGRAM_BOT_TOKEN is for trading sends)"
                )
                return atp
    except Exception:
        pass

    token = (os.getenv("TELEGRAM_BOT_TOKEN") or "").strip()
    if token:
        return token

    token = (os.getenv("TELEGRAM_BOT_TOKEN_DEV") or "").strip()
    if token:
        return token

    token = (os.getenv("TELEGRAM_ATP_CONTROL_BOT_TOKEN") or "").strip()
    if token:
        logger.info("[TG] Using TELEGRAM_ATP_CONTROL_BOT_TOKEN for polling (TELEGRAM_BOT_TOKEN not set)")
        return token

    token = (os.getenv("TELEGRAM_CLAW_BOT_TOKEN") or "").strip()
    if token:
        logger.info("[TG] Using TELEGRAM_CLAW_BOT_TOKEN for polling (TELEGRAM_BOT_TOKEN not set)")
        return token

    logger.info("[TG] No token in env - prompting operator for Telegram Bot Token")
    token = _get_token_interactive()
    if token:
        logger.info("[TG] Token received via interactive prompt (masked: %s)", mask_token(token))
    else:
        logger.warning("[TG] No token provided - Telegram disabled")
    return token


def get_telegram_token_dev() -> Optional[str]:
    """
    Get the optional dev token for local development (avoids 409 conflicts with AWS).
    Only from env; never prompts.
    """
    return (os.getenv("TELEGRAM_BOT_TOKEN_DEV") or "").strip() or None


def get_telegram_token_source() -> str:
    """
    Return which env var provided the active polling token (for audit logging).
    Matches the priority in get_telegram_token().
    """
    try:
        from app.core.runtime import is_aws_runtime

        if is_aws_runtime() and (os.getenv("TELEGRAM_ATP_CONTROL_BOT_TOKEN") or "").strip():
            return "TELEGRAM_ATP_CONTROL_BOT_TOKEN"
    except Exception:
        pass
    if (os.getenv("TELEGRAM_BOT_TOKEN") or "").strip():
        return "TELEGRAM_BOT_TOKEN"
    if (os.getenv("TELEGRAM_BOT_TOKEN_DEV") or "").strip():
        return "TELEGRAM_BOT_TOKEN_DEV"
    if (os.getenv("TELEGRAM_ATP_CONTROL_BOT_TOKEN") or "").strip():
        return "TELEGRAM_ATP_CONTROL_BOT_TOKEN"
    if (os.getenv("TELEGRAM_CLAW_BOT_TOKEN") or "").strip():
        return "TELEGRAM_CLAW_BOT_TOKEN"
    return "interactive_prompt"
