"""Tests for Jarvis Phase B Send to LAB (isolated sandbox trial)."""

from __future__ import annotations

from unittest.mock import patch

import pytest
from fastapi import FastAPI
from fastapi.testclient import TestClient
from sqlalchemy import create_engine
from sqlalchemy.pool import StaticPool

from app.api.routes_jarvis import router as jarvis_router
from app.database import (
    ensure_jarvis_execution_log_table,
    ensure_jarvis_task_approvals_table,
    ensure_jarvis_task_runs_table,
)
from app.jarvis.artifacts.storage import create_versioned_artifact
from app.jarvis.change_execution.config import jarvis_lab_trial_enabled, phase5_safety_status
from app.jarvis.change_execution.lab_trial import (
    assess_lab_eligibility,
    get_lab_trial_status,
    send_to_lab,
)
from app.jarvis.change_execution.patch_quality import is_stub_patch, stub_refusal_message
from app.jarvis.execution import audit as audit_mod
from app.jarvis.execution import persistence as persist_mod
from app.jarvis.execution.lifecycle import TaskLifecycleState
from app.jarvis.execution.persistence import (
    create_execution_task,
    get_execution_task,
    transition_task_status,
    _update_task,
)


REAL_PATCH = """\
--- a/docs/README.md
+++ b/docs/README.md
@@ -1,3 +1,4 @@
 # ATP
+
+# LAB trial marker
 Docs
"""

STUB_PATCH = """\
--- a/backend/app/jarvis/execution/service.py
+++ b/backend/app/jarvis/execution/service.py
@@ -1,3 +1,6 @@
 # Jarvis Phase 4 proposed patch (NOT APPLIED)
 # Objective: update something
+# TODO: implement validated change behind approval gate
+# Generated by patch_agent — requires human approval before application
"""


@pytest.fixture()
def exec_db(monkeypatch, tmp_path):
    engine = create_engine(
        "sqlite://",
        connect_args={"check_same_thread": False},
        poolclass=StaticPool,
        future=True,
    )
    ensure_jarvis_task_runs_table(engine)
    ensure_jarvis_execution_log_table(engine)
    ensure_jarvis_task_approvals_table(engine)
    monkeypatch.setattr(persist_mod, "engine", engine)
    monkeypatch.setattr(audit_mod, "engine", engine)
    from app.jarvis import artifacts as artifacts_pkg

    monkeypatch.setattr(artifacts_pkg.storage, "_ARTIFACTS_DIR", tmp_path)
    yield engine
    engine.dispose()


@pytest.fixture()
def jarvis_client(exec_db, monkeypatch, tmp_path):
    monkeypatch.setenv("JARVIS_ENABLED", "true")
    monkeypatch.setenv("JARVIS_DRY_RUN_ONLY", "true")
    monkeypatch.setenv("JARVIS_PATCH_APPLY_ENABLED", "false")
    monkeypatch.setenv("JARVIS_PR_CREATION_ENABLED", "false")
    monkeypatch.setenv("JARVIS_GITHUB_WRITE_ENABLED", "false")
    monkeypatch.setenv("JARVIS_LAB_TRIAL_ENABLED", "true")
    import app.database as db_mod

    monkeypatch.setattr(db_mod, "engine", exec_db)
    from app.jarvis import artifacts as artifacts_pkg

    monkeypatch.setattr(artifacts_pkg.storage, "_ARTIFACTS_DIR", tmp_path)
    app = FastAPI()
    app.include_router(jarvis_router)
    return TestClient(app)


def _seed_waiting_task(patch_content: str, *, workflow: str = "phase4b_patch_proposal") -> str:
    task_id = "lab-trial-0001-aaaa-bbbb-cccccccccccc"
    create_execution_task(task_id=task_id, objective="Try real patch in LAB", dry_run=True)
    art = create_versioned_artifact(
        task_id=task_id,
        name="patch.diff",
        content=patch_content,
        fmt="text",
        version=1,
    )
    _update_task(
        task_id,
        plan_json={"workflow_type": workflow},
        artifacts_json=[art],
        approval_required=True,
        approval_status="pending",
    )
    transition_task_status(task_id, TaskLifecycleState.PLANNING)
    transition_task_status(task_id, TaskLifecycleState.INVESTIGATING)
    transition_task_status(task_id, TaskLifecycleState.PATCH_READY)
    transition_task_status(task_id, TaskLifecycleState.REVIEWING)
    transition_task_status(task_id, TaskLifecycleState.WAITING_FOR_APPROVAL)
    return task_id


def test_is_stub_patch_detects_phase4_placeholder():
    assert is_stub_patch(STUB_PATCH) is True
    assert is_stub_patch("") is True
    assert is_stub_patch(REAL_PATCH) is False


def test_lab_trial_enabled_by_default(monkeypatch):
    monkeypatch.delenv("JARVIS_LAB_TRIAL_ENABLED", raising=False)
    assert jarvis_lab_trial_enabled() is True
    status = phase5_safety_status()
    assert status["lab_trial_enabled"] is True
    assert status["patch_apply_enabled"] is False


def test_assess_refuses_stub(exec_db):
    task_id = _seed_waiting_task(STUB_PATCH)
    task = get_execution_task(task_id)
    eligibility = assess_lab_eligibility(task)
    assert eligibility["can_send_to_lab"] is False
    assert "stub" in eligibility["reason"].lower() or "No real patch" in eligibility["reason"]


def test_send_to_lab_refuses_stub_without_gate1_flag(exec_db, monkeypatch):
    monkeypatch.setenv("JARVIS_ENABLED", "true")
    monkeypatch.setenv("JARVIS_PATCH_APPLY_ENABLED", "false")
    task_id = _seed_waiting_task(STUB_PATCH)
    with pytest.raises(ValueError, match="No real patch|stub"):
        send_to_lab(task_id, actor_id="tester")
    lab = get_lab_trial_status(task_id)
    assert lab["status"] == "refused"
    assert lab["can_send_to_lab"] is False


def test_send_to_lab_applies_and_passes(exec_db, monkeypatch):
    monkeypatch.setenv("JARVIS_ENABLED", "true")
    monkeypatch.setenv("JARVIS_PATCH_APPLY_ENABLED", "false")
    task_id = _seed_waiting_task(REAL_PATCH)

    mock_apply = {
        "success": True,
        "branch_name": "jarvis/task-labtrial",
        "workdir": "/tmp/jarvis-sandbox/lab-trial",
        "changed_files": ["docs/README.md"],
        "forbidden_check": {"passed": True, "blocked_paths": []},
        "applied_patch_path": "/tmp/jarvis-sandbox/lab-trial/applied_patch.diff",
    }
    mock_tests = {
        "passed": True,
        "backend_tests": {"ok": True},
        "backend_summary": "Passed",
        "frontend_build": {"skipped": True},
        "worktree_validation": {"clean": True},
        "changed_files": ["docs/README.md"],
    }

    with (
        patch("app.jarvis.change_execution.lab_trial.apply_patch_in_sandbox", return_value=mock_apply),
        patch("app.jarvis.change_execution.lab_trial.run_sandbox_tests", return_value=mock_tests),
        patch("app.jarvis.change_execution.lab_trial.write_test_artifacts", return_value={}),
        patch("pathlib.Path.read_text", return_value=REAL_PATCH),
    ):
        result = send_to_lab(task_id, actor_id="tester", comment="lab please")

    assert result["status"] == TaskLifecycleState.WAITING_FOR_PR_APPROVAL.value
    assert result["current_step"] == "lab_passed_awaiting_promote"
    lab = result["lab_trial"]
    assert lab["status"] == "passed"
    assert lab["tests_passed"] is True
    assert lab["can_promote"] is True
    assert lab["promote_available"] is False
    assert "isolated sandbox" in lab["mechanism_label"].lower()
    # Prod Gate-1 flag stayed irrelevant / off
    assert lab["safety_flags"]["patch_apply_enabled"] is False


def test_send_to_lab_api_route(jarvis_client, monkeypatch):
    monkeypatch.setenv("JARVIS_ENABLED", "true")
    task_id = _seed_waiting_task(REAL_PATCH)
    mock_apply = {
        "success": True,
        "branch_name": "jarvis/task-api",
        "workdir": "/tmp/jarvis-sandbox/api",
        "changed_files": ["docs/README.md"],
        "forbidden_check": {"passed": True, "blocked_paths": []},
        "applied_patch_path": "/tmp/jarvis-sandbox/api/applied_patch.diff",
    }
    mock_tests = {"passed": True, "changed_files": ["docs/README.md"]}

    with (
        patch("app.jarvis.change_execution.lab_trial.apply_patch_in_sandbox", return_value=mock_apply),
        patch("app.jarvis.change_execution.lab_trial.run_sandbox_tests", return_value=mock_tests),
        patch("app.jarvis.change_execution.lab_trial.write_test_artifacts", return_value={}),
        patch("pathlib.Path.read_text", return_value=REAL_PATCH),
    ):
        resp = jarvis_client.post(
            f"/api/jarvis/tasks/change/{task_id}/send-to-lab",
            json={"actor_id": "dashboard", "comment": "go"},
        )
    assert resp.status_code == 200, resp.text
    body = resp.json()
    assert body["lab_trial"]["status"] == "passed"

    status_resp = jarvis_client.get(f"/api/jarvis/tasks/change/{task_id}/lab-status")
    assert status_resp.status_code == 200
    assert status_resp.json()["status"] == "passed"


def test_send_to_lab_api_refuses_stub(jarvis_client):
    task_id = _seed_waiting_task(STUB_PATCH)
    resp = jarvis_client.post(
        f"/api/jarvis/tasks/change/{task_id}/send-to-lab",
        json={"actor_id": "dashboard"},
    )
    assert resp.status_code == 409
    assert "real patch" in resp.json()["detail"].lower() or "stub" in resp.json()["detail"].lower()


def test_stub_refusal_message_mentions_4b():
    msg = stub_refusal_message()
    assert "4B" in msg or "stub" in msg.lower()
