"""Tests for Jarvis Phase C Promote to production (open PR after LAB green)."""

from __future__ import annotations

from unittest.mock import patch

import pytest
from fastapi import FastAPI
from fastapi.testclient import TestClient
from sqlalchemy import create_engine
from sqlalchemy.pool import StaticPool

from app.api.routes_jarvis import router as jarvis_router
from app.database import (
    ensure_jarvis_execution_log_table,
    ensure_jarvis_task_approvals_table,
    ensure_jarvis_task_runs_table,
)
from app.jarvis.artifacts.storage import create_versioned_artifact
from app.jarvis.change_execution.config import jarvis_promote_pr_enabled, phase5_safety_status
from app.jarvis.change_execution.lab_trial import (
    get_lab_trial_status,
    promote_to_production,
    send_to_lab,
)
from app.jarvis.execution import audit as audit_mod
from app.jarvis.execution import persistence as persist_mod
from app.jarvis.execution.lifecycle import TaskLifecycleState
from app.jarvis.execution.persistence import (
    create_execution_task,
    get_execution_task,
    transition_task_status,
    _update_task,
)
from app.jarvis.github.pr_service import check_lab_promote_pr_allowed


REAL_PATCH = """\
--- a/docs/README.md
+++ b/docs/README.md
@@ -1,3 +1,4 @@
 # ATP
+
+# LAB trial marker
 Docs
"""

STUB_PATCH = """\
--- a/backend/app/jarvis/execution/service.py
+++ b/backend/app/jarvis/execution/service.py
@@ -1,3 +1,6 @@
 # Jarvis Phase 4 proposed patch (NOT APPLIED)
 # Objective: update something
+# TODO: implement validated change behind approval gate
+# Generated by patch_agent — requires human approval before application
"""


@pytest.fixture()
def exec_db(monkeypatch, tmp_path):
    engine = create_engine(
        "sqlite://",
        connect_args={"check_same_thread": False},
        poolclass=StaticPool,
        future=True,
    )
    ensure_jarvis_task_runs_table(engine)
    ensure_jarvis_execution_log_table(engine)
    ensure_jarvis_task_approvals_table(engine)
    monkeypatch.setattr(persist_mod, "engine", engine)
    monkeypatch.setattr(audit_mod, "engine", engine)
    from app.jarvis import artifacts as artifacts_pkg

    monkeypatch.setattr(artifacts_pkg.storage, "_ARTIFACTS_DIR", tmp_path)
    yield engine
    engine.dispose()


@pytest.fixture()
def jarvis_client(exec_db, monkeypatch, tmp_path):
    monkeypatch.setenv("JARVIS_ENABLED", "true")
    monkeypatch.setenv("JARVIS_DRY_RUN_ONLY", "true")
    monkeypatch.setenv("JARVIS_PATCH_APPLY_ENABLED", "false")
    monkeypatch.setenv("JARVIS_PR_CREATION_ENABLED", "false")
    monkeypatch.setenv("JARVIS_GITHUB_WRITE_ENABLED", "false")
    monkeypatch.setenv("JARVIS_LAB_TRIAL_ENABLED", "true")
    monkeypatch.setenv("JARVIS_PROMOTE_PR_ENABLED", "false")
    import app.database as db_mod

    monkeypatch.setattr(db_mod, "engine", exec_db)
    from app.jarvis import artifacts as artifacts_pkg

    monkeypatch.setattr(artifacts_pkg.storage, "_ARTIFACTS_DIR", tmp_path)
    app = FastAPI()
    app.include_router(jarvis_router)
    return TestClient(app)


def _seed_waiting_task(patch_content: str, *, workflow: str = "phase4b_patch_proposal") -> str:
    task_id = "lab-promote-0001-aaaa-bbbb-cccccccccccc"
    create_execution_task(task_id=task_id, objective="Promote after LAB", dry_run=True)
    art = create_versioned_artifact(
        task_id=task_id,
        name="patch.diff",
        content=patch_content,
        fmt="text",
        version=1,
    )
    _update_task(
        task_id,
        plan_json={"workflow_type": workflow},
        artifacts_json=[art],
        approval_required=True,
        approval_status="pending",
    )
    transition_task_status(task_id, TaskLifecycleState.PLANNING)
    transition_task_status(task_id, TaskLifecycleState.INVESTIGATING)
    transition_task_status(task_id, TaskLifecycleState.PATCH_READY)
    transition_task_status(task_id, TaskLifecycleState.REVIEWING)
    transition_task_status(task_id, TaskLifecycleState.WAITING_FOR_APPROVAL)
    return task_id


def _run_lab_pass(task_id: str, monkeypatch) -> dict:
    monkeypatch.setenv("JARVIS_ENABLED", "true")
    monkeypatch.setenv("JARVIS_PATCH_APPLY_ENABLED", "false")
    mock_apply = {
        "success": True,
        "branch_name": "jarvis/task-labpromote",
        "workdir": "/tmp/jarvis-sandbox/lab-promote",
        "changed_files": ["docs/README.md"],
        "forbidden_check": {"passed": True, "blocked_paths": []},
        "applied_patch_path": "/tmp/jarvis-sandbox/lab-promote/applied_patch.diff",
    }
    mock_tests = {
        "passed": True,
        "backend_tests": {"ok": True},
        "backend_summary": "Passed",
        "frontend_build": {"skipped": True},
        "worktree_validation": {"clean": True},
        "changed_files": ["docs/README.md"],
    }
    with (
        patch("app.jarvis.change_execution.lab_trial.apply_patch_in_sandbox", return_value=mock_apply),
        patch("app.jarvis.change_execution.lab_trial.run_sandbox_tests", return_value=mock_tests),
        patch("app.jarvis.change_execution.lab_trial.write_test_artifacts", return_value={}),
        patch("pathlib.Path.read_text", return_value=REAL_PATCH),
    ):
        return send_to_lab(task_id, actor_id="tester")


def test_promote_pr_disabled_by_default(monkeypatch):
    monkeypatch.delenv("JARVIS_PROMOTE_PR_ENABLED", raising=False)
    assert jarvis_promote_pr_enabled() is False
    flags = phase5_safety_status()
    assert flags["promote_pr_enabled"] is False
    assert flags["pr_creation_enabled"] is False
    assert flags["github_write_enabled"] is False


def test_check_lab_promote_pr_allowed_scoped(monkeypatch):
    monkeypatch.setenv("JARVIS_PROMOTE_PR_ENABLED", "true")
    monkeypatch.setenv("JARVIS_PR_CREATION_ENABLED", "false")
    monkeypatch.setenv("JARVIS_GITHUB_WRITE_ENABLED", "false")
    ok = check_lab_promote_pr_allowed(
        lab_passed=True,
        tests_passed=True,
        patch_safety_passed=True,
        stub_patch=False,
        already_promoted=False,
    )
    assert ok["allowed"] is True


def test_promote_blocked_when_flag_off(exec_db, monkeypatch):
    monkeypatch.setenv("JARVIS_PROMOTE_PR_ENABLED", "false")
    task_id = _seed_waiting_task(REAL_PATCH)
    _run_lab_pass(task_id, monkeypatch)
    lab = get_lab_trial_status(task_id)
    assert lab["can_promote"] is True
    assert lab["promote_available"] is False
    assert "JARVIS_PROMOTE_PR_ENABLED" in lab["promote_hint"]

    with pytest.raises(RuntimeError, match="JARVIS_PROMOTE_PR_ENABLED"):
        promote_to_production(task_id, actor_id="tester")


def test_promote_opens_mock_pr_after_lab_green(exec_db, monkeypatch):
    monkeypatch.setenv("JARVIS_PROMOTE_PR_ENABLED", "true")
    monkeypatch.setenv("JARVIS_PR_CREATION_ENABLED", "false")
    monkeypatch.setenv("JARVIS_GITHUB_WRITE_ENABLED", "false")
    task_id = _seed_waiting_task(REAL_PATCH)
    _run_lab_pass(task_id, monkeypatch)

    lab = get_lab_trial_status(task_id)
    assert lab["promote_available"] is True

    result = promote_to_production(task_id, actor_id="tester", mock_pr=True)
    assert result["status"] == TaskLifecycleState.COMPLETED.value
    assert result["current_step"] == "lab_promoted_awaiting_human_merge"
    assert "merge" in (result.get("final_answer") or "").lower()
    lab = result["lab_trial"]
    assert lab["status"] == "promoted"
    assert lab["pr_url"]
    assert lab["can_promote"] is False
    assert lab["promote_available"] is False
    # Broad Gate-2 flags stayed off
    assert lab["safety_flags"]["pr_creation_enabled"] is False
    assert lab["safety_flags"]["github_write_enabled"] is False


def test_promote_refuses_before_lab(exec_db, monkeypatch):
    monkeypatch.setenv("JARVIS_ENABLED", "true")
    monkeypatch.setenv("JARVIS_PROMOTE_PR_ENABLED", "true")
    task_id = _seed_waiting_task(REAL_PATCH)
    with pytest.raises(ValueError, match="LAB must pass|not ready"):
        promote_to_production(task_id, actor_id="tester", mock_pr=True)


def test_promote_refuses_stub(exec_db, monkeypatch):
    monkeypatch.setenv("JARVIS_ENABLED", "true")
    monkeypatch.setenv("JARVIS_PROMOTE_PR_ENABLED", "true")
    task_id = _seed_waiting_task(STUB_PATCH)
    # Force a lab-passed state without send_to_lab (which would refuse stub).
    task = get_execution_task(task_id)
    plan = dict(task.get("plan") or {})
    plan["lab_trial"] = {
        "status": "passed",
        "tests_passed": True,
        "sandbox_applied": True,
        "branch_name": "jarvis/task-stub",
        "workdir": "/tmp/x",
        "forbidden_check": {"passed": True},
    }
    _update_task(task_id, plan_json=plan)
    transition_task_status(task_id, TaskLifecycleState.APPLYING_PATCH)
    transition_task_status(task_id, TaskLifecycleState.SANDBOX_TESTING)
    transition_task_status(task_id, TaskLifecycleState.WAITING_FOR_PR_APPROVAL)
    from app.jarvis.execution.persistence import record_approval

    record_approval(task_id=task_id, decision="sent_to_lab", actor_id="tester", comment="forced")
    with pytest.raises(ValueError, match="stub|real patch"):
        promote_to_production(task_id, actor_id="tester", mock_pr=True)


def test_promote_api_route(jarvis_client, monkeypatch):
    monkeypatch.setenv("JARVIS_PROMOTE_PR_ENABLED", "true")
    task_id = _seed_waiting_task(REAL_PATCH)
    _run_lab_pass(task_id, monkeypatch)

    with patch(
        "app.jarvis.change_execution.lab_trial.create_pull_request",
        return_value={
            "success": True,
            "pr_url": "https://github.com/ccruz0/crypto-2.0/pull/999",
            "mock": True,
            "merge": False,
            "deploy": False,
        },
    ), patch(
        "app.jarvis.change_execution.lab_trial.prepare_sandbox_branch_for_push",
        return_value={"ok": True},
    ):
        resp = jarvis_client.post(
            f"/api/jarvis/tasks/change/{task_id}/promote",
            json={"actor_id": "dashboard", "comment": "ship it"},
        )
    assert resp.status_code == 200, resp.text
    body = resp.json()
    assert body["lab_trial"]["status"] == "promoted"
    assert "pull/999" in body["lab_trial"]["pr_url"]
    assert "Merge" in body["final_answer"] or "merge" in body["final_answer"].lower()


def test_promote_api_blocked_when_flag_off(jarvis_client, monkeypatch):
    monkeypatch.setenv("JARVIS_PROMOTE_PR_ENABLED", "false")
    task_id = _seed_waiting_task(REAL_PATCH)
    _run_lab_pass(task_id, monkeypatch)
    resp = jarvis_client.post(
        f"/api/jarvis/tasks/change/{task_id}/promote",
        json={"actor_id": "dashboard"},
    )
    assert resp.status_code == 403
    assert "JARVIS_PROMOTE_PR_ENABLED" in resp.json()["detail"]


def test_prepare_sandbox_stages_only_changed_files(tmp_path, monkeypatch):
    """Promote must not git-add sandbox artifacts (approved.patch, etc.)."""
    import subprocess

    from app.jarvis.github import pr_service as prs

    repo = tmp_path / "sandbox"
    repo.mkdir()
    subprocess.run(["git", "init"], cwd=repo, check=True, capture_output=True)
    subprocess.run(["git", "config", "user.email", "t@example.com"], cwd=repo, check=True)
    subprocess.run(["git", "config", "user.name", "t"], cwd=repo, check=True)
    target = repo / "docs"
    target.mkdir()
    (target / "README.md").write_text("# hi\n", encoding="utf-8")
    subprocess.run(["git", "add", "."], cwd=repo, check=True, capture_output=True)
    subprocess.run(["git", "commit", "-m", "init"], cwd=repo, check=True, capture_output=True)
    (target / "README.md").write_text("# hi\n# patch\n", encoding="utf-8")
    (repo / "approved.patch").write_text("JUNK\n", encoding="utf-8")
    (repo / "test_results.json").write_text("{}\n", encoding="utf-8")

    # Point workspace remote resolution at this sandbox.
    monkeypatch.setattr(prs, "workspace_root", lambda: repo)
    subprocess.run(
        ["git", "remote", "add", "origin", "git@github.com:ccruz0/crypto-2.0.git"],
        cwd=repo,
        check=True,
        capture_output=True,
    )

    out = prs.prepare_sandbox_branch_for_push(
        workdir=repo,
        branch_name="jarvis/test-promote",
        commit_message="promote test",
        changed_files=["docs/README.md"],
    )
    assert out.get("ok") is True, out

    names = subprocess.check_output(
        ["git", "show", "--name-only", "--pretty=format:", "HEAD"],
        cwd=repo,
        text=True,
    )
    assert "docs/README.md" in names
    assert "approved.patch" not in names
    assert "test_results.json" not in names


def test_prepare_sandbox_rejects_empty_changed_files(tmp_path, monkeypatch):
    import subprocess

    from app.jarvis.github import pr_service as prs

    repo = tmp_path / "sandbox"
    repo.mkdir()
    subprocess.run(["git", "init"], cwd=repo, check=True, capture_output=True)
    subprocess.run(["git", "config", "user.email", "t@example.com"], cwd=repo, check=True)
    subprocess.run(["git", "config", "user.name", "t"], cwd=repo, check=True)
    (repo / "f.txt").write_text("x\n", encoding="utf-8")
    subprocess.run(["git", "add", "."], cwd=repo, check=True, capture_output=True)
    subprocess.run(["git", "commit", "-m", "init"], cwd=repo, check=True, capture_output=True)
    monkeypatch.setattr(prs, "workspace_root", lambda: repo)
    subprocess.run(
        ["git", "remote", "add", "origin", "git@github.com:ccruz0/crypto-2.0.git"],
        cwd=repo,
        check=True,
        capture_output=True,
    )
    out = prs.prepare_sandbox_branch_for_push(
        workdir=repo,
        branch_name="jarvis/empty",
        commit_message="x",
        changed_files=[],
    )
    assert out.get("ok") is False
    assert "empty" in (out.get("error") or "").lower()
