"""Patch generation agent for Jarvis Phase 4 (no automatic application)."""

from __future__ import annotations

import hashlib
import uuid
from datetime import datetime, timezone
from typing import Any

from app.jarvis.execution.safety import SafetyLevel, classify_phase4_action


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def _infer_target_files(objective: str, repository_analysis: dict[str, Any]) -> list[str]:
    explicit = repository_analysis.get("target_files") or []
    if explicit:
        return list(explicit)
    objective_l = objective.lower()
    candidates: list[str] = []
    for module in repository_analysis.get("modules", []):
        path = module.get("path", "")
        if not path:
            continue
        if any(k in objective_l for k in ("deploy", "validation", "jarvis", "routes")):
            if "jarvis" in path or "deploy" in path or "routes" in path:
                candidates.append(path)
        if "websocket" in objective_l and "websocket" in path.lower():
            candidates.append(path)
        if "openclaw" in objective_l and "openclaw" in path.lower():
            candidates.append(path)
    if not candidates:
        for hit in repository_analysis.get("findings", {}).values():
            if isinstance(hit, list):
                for item in hit[:3]:
                    p = item.get("path", "")
                    if p and p not in candidates:
                        candidates.append(p)
    return candidates[:5] or ["backend/app/jarvis/execution/service.py"]


def _build_unified_diff(objective: str, target_files: list[str]) -> str:
    """Generate a proposed unified diff (never applied automatically)."""
    lines: list[str] = []
    for path in target_files:
        lines.extend(
            [
                f"--- a/{path}",
                f"+++ b/{path}",
                "@@ -1,3 +1,6 @@",
                " # Jarvis Phase 4 proposed patch (NOT APPLIED)",
                f" # Objective: {objective[:120]}",
                "+# TODO: implement validated change behind approval gate",
                "+# Generated by patch_agent — requires human approval before application",
                "",
            ]
        )
    return "\n".join(lines)


def _assess_risk(objective: str, target_files: list[str], diff: str) -> dict[str, Any]:
    objective_l = objective.lower()
    score = 20
    factors: list[str] = []
    if any(k in objective_l for k in ("deploy", "production", "nginx")):
        score += 30
        factors.append("deployment-related objective")
    if len(target_files) > 3:
        score += 15
        factors.append("multiple files affected")
    if "routes" in " ".join(target_files):
        score += 10
        factors.append("API route changes possible")
    if classify_phase4_action("patch_application") == SafetyLevel.NEEDS_APPROVAL:
        factors.append("patch application requires approval")
    level = "low"
    if score >= 60:
        level = "high"
    elif score >= 40:
        level = "medium"
    return {"risk_score": min(score, 100), "risk_level": level, "factors": factors}


def create_patch(
    *,
    objective: str,
    repository_analysis: dict[str, Any],
    target_files: list[str] | None = None,
) -> dict[str, Any]:
    """Create a new patch artifact envelope (no file writes)."""
    files = target_files or _infer_target_files(objective, repository_analysis)
    diff = _build_unified_diff(objective, files)
    risk = _assess_risk(objective, files, diff)
    patch_id = str(uuid.uuid4())
    revision = 1
    content_hash = hashlib.sha256(diff.encode()).hexdigest()[:16]
    return {
        "patch_id": patch_id,
        "revision": revision,
        "objective": objective,
        "target_files": files,
        "unified_diff": diff,
        "patch_summary": f"Proposed change for: {objective[:200]} ({len(files)} file(s))",
        "risk_assessment": risk,
        "estimated_impact": {
            "files_affected": len(files),
            "lines_added_estimate": diff.count("\n+"),
            "requires_approval": True,
            "auto_apply": False,
        },
        "content_hash": content_hash,
        "safety_level": classify_phase4_action("patch_generation").value,
        "created_at": _now_iso(),
        "read_only": True,
    }


def update_patch(existing: dict[str, Any], *, objective: str | None = None, notes: str = "") -> dict[str, Any]:
    """Create a new revision of an existing patch."""
    rev = int(existing.get("revision", 1)) + 1
    obj = objective or existing.get("objective", "")
    files = existing.get("target_files", [])
    diff = _build_unified_diff(obj, files)
    if notes:
        diff = f"# Revision {rev}: {notes}\n" + diff
    updated = dict(existing)
    updated.update(
        {
            "revision": rev,
            "objective": obj,
            "unified_diff": diff,
            "patch_summary": f"[rev {rev}] {existing.get('patch_summary', obj)}",
            "content_hash": hashlib.sha256(diff.encode()).hexdigest()[:16],
            "updated_at": _now_iso(),
            "previous_revision": existing.get("revision", 1),
        }
    )
    updated["risk_assessment"] = _assess_risk(obj, files, diff)
    return updated


def compare_patch_revisions(left: dict[str, Any], right: dict[str, Any]) -> dict[str, Any]:
    """Compare two patch revisions."""
    left_diff = left.get("unified_diff", "")
    right_diff = right.get("unified_diff", "")
    left_lines = set(left_diff.splitlines())
    right_lines = set(right_diff.splitlines())
    return {
        "left_revision": left.get("revision"),
        "right_revision": right.get("revision"),
        "lines_only_in_left": len(left_lines - right_lines),
        "lines_only_in_right": len(right_lines - left_lines),
        "files_changed": list(set(left.get("target_files", [])) ^ set(right.get("target_files", []))),
        "risk_delta": (right.get("risk_assessment", {}).get("risk_score", 0) - left.get("risk_assessment", {}).get("risk_score", 0)),
    }
