"""Detect stub / non-actionable patch diffs before LAB trial apply."""

from __future__ import annotations

# Markers emitted by Phase 4 patch_agent stub generator (not a real change).
_STUB_MARKERS = (
    "# TODO: implement validated change behind approval gate",
    "Generated by patch_agent — requires human approval before application",
    "Jarvis Phase 4 proposed patch (NOT APPLIED)",
)


def is_stub_patch(patch_content: str) -> bool:
    """Return True when the patch is empty or a Phase-4 TODO placeholder.

    Marker checks look only at added (+) / removed (-) content lines so that
    legitimate patches whose *context* mentions stub wording are not refused.
    """
    text = (patch_content or "").strip()
    if not text:
        return True
    # Unified diffs need at least one added/removed content line beyond headers.
    content_lines = [
        ln
        for ln in text.splitlines()
        if ln.startswith(("+", "-")) and not ln.startswith(("+++", "---"))
    ]
    if not content_lines:
        return True
    joined = "\n".join(content_lines).lower()
    if any(marker.lower() in joined for marker in _STUB_MARKERS):
        return True
    # All content lines are comments / placeholders → still a stub.
    meaningful = [
        ln
        for ln in content_lines
        if not ln[1:].lstrip().startswith("# TODO")
        and "implement validated change" not in ln.lower()
    ]
    return len(meaningful) == 0


def stub_refusal_message() -> str:
    return (
        "No real patch yet — this artifact is a stub/TODO placeholder from the Patch agent. "
        "Send to LAB refuses stub diffs. Use a Phase 4B proposal (Diagnostics → Generate Patch "
        "Proposal) or wait until a real patch is available."
    )
