#!/usr/bin/env bash
#
# extract_jarvis_env.sh (R6, point 1)
#
# Produce the Jarvis runner's environment file (.env.jarvis) carrying ONLY the
# keys the runner legitimately needs from a shared source env: Notion and
# OpenClaw. It deliberately never copies AWS/Bedrock credentials — the runner
# gets those from the EC2 instance role via the boto3 default chain over IMDS
# (see PR #463). Copying static AWS_* here would both reintroduce the credential
# boundary crossing and let a stale env value silently win over the role.
#
# Usage:
#   extract_jarvis_env.sh <source-env-file> [<output-file>]
# Defaults:
#   output-file = .env.jarvis (in the current directory)
#
# Behaviour:
#   - Emits only the allowlisted keys, in a stable order.
#   - If a required key is absent from the source, it is skipped (not emitted
#     empty) and reported on stderr, so a missing Notion token is visible.
#   - If any AWS_* key is present in the source, it is explicitly NOT written and
#     a warning is printed — the runner must not carry them.
#   - Output is created with 0600 permissions.

set -euo pipefail

SRC="${1:-}"
OUT="${2:-.env.jarvis}"

if [[ -z "${SRC}" ]]; then
  echo "usage: $0 <source-env-file> [<output-file>]" >&2
  exit 2
fi
if [[ ! -f "${SRC}" ]]; then
  echo "error: source env file not found: ${SRC}" >&2
  exit 2
fi

# Allowlist: only these prefixes are carried into the runner env.
ALLOW_KEYS=(
  NOTION_API_KEY
  NOTION_TOKEN
  NOTION_DATABASE_ID
  NOTION_VERSION
  OPENCLAW_API_KEY
  OPENCLAW_BASE_URL
  OPENCLAW_TOKEN
)

# Read a single KEY=VALUE from the source, preserving the value verbatim.
read_key() {
  local key="$1"
  # Match "KEY=" at line start, ignore commented lines, take the last occurrence.
  grep -E "^${key}=" "${SRC}" 2>/dev/null | grep -v '^\s*#' | tail -n 1 || true
}

umask 077
: > "${OUT}"

{
  echo "# Generated by extract_jarvis_env.sh — Notion + OpenClaw only."
  echo "# AWS/Bedrock credentials are intentionally excluded: the runner uses the"
  echo "# EC2 instance role via the boto3 default chain (IMDS). Do not add AWS_* here."
  echo "# Region, if the runner needs it explicitly, is set separately (not a credential)."
} >> "${OUT}"

emitted=0
for key in "${ALLOW_KEYS[@]}"; do
  line="$(read_key "${key}")"
  if [[ -n "${line}" ]]; then
    echo "${line}" >> "${OUT}"
    emitted=$((emitted + 1))
  else
    echo "note: key not present in source, skipped: ${key}" >&2
  fi
done

# Guardrail: loudly refuse to have leaked any AWS credential into the output.
if grep -Eq '^(AWS_ACCESS_KEY_ID|AWS_SECRET_ACCESS_KEY|AWS_SESSION_TOKEN)=' "${OUT}"; then
  echo "error: AWS credential leaked into ${OUT} — aborting" >&2
  exit 1
fi

# Advisory: warn if the SOURCE still carries static AWS creds (not our job to fix,
# but worth surfacing during the instance-role cutover).
if grep -Eq '^(AWS_ACCESS_KEY_ID|AWS_SECRET_ACCESS_KEY)=' "${SRC}" 2>/dev/null; then
  echo "warning: source ${SRC} still contains static AWS_* keys; the runner does not" >&2
  echo "         need them (instance role via IMDS) and they were not copied." >&2
fi

chmod 600 "${OUT}"
echo "wrote ${OUT} (${emitted} keys: Notion/OpenClaw only, no AWS/Bedrock)" >&2
